### PR TITLE
[ONNX CI] CI Improvements

### PR DESCRIPTION
**Pull request by mchrusci**
* export NGRAPH_ONNX_IMPORT_ENABLE="TRUE"
  related to: https://github.com/NervanaSystems/ngraph/pull/1687#pullrequestreview-164636979
* Link ONNX models directory instead of copying
* Link to Blue Ocean in notification e-mail
* Added option to specify nGraph commit being used during manual repro

### CODE REVIEW

**Comment by mchrusci** [comment]
CLEAR CACHE

**Comment by mchrusci** [comment]
TEST NOW

**Comment by mchrusci** [comment]
CLEAR CACHE

**Comment by mchrusci** [comment]
TEST NOW

**Comment by postrational** [comment]
TEST NOW

**Pull request merged**
