### PR TITLE
[CI] Apply PEP8 style guide to Watchdog code

### PR DESCRIPTION
**Pull request by postrational**

### CODE REVIEW

**Comment by postrational** [comment]
@mchrusci Please add a fix for `C901 'Watchdog._interpret_statuses' is too complex (8)` by reducing the cyclomatic complexity of the `_interpret_statuses` function.

**Comment by mchrusci** [comment]
TEST_NOW

**Comment by mchrusci** [comment]
CLEAR CACHE

**Comment by mchrusci** [comment]
TEST NOW

**Pull request merged**
